### ISSUE TITLE
Streaming API使いたい

### ISSUE THREAD

**Issue by neruneru0419** [ayme01/yukimi_learning_for_misskey#7]
https://misskey-hub.net/docs/api/streaming/
リアルタイムでノートの投稿とかフォロバとかしたいと思っています
どうでしょうか

**Comment by ayok01** [comment]
いいと思うけどTLの取得とか、投稿はストリーミングじゃなくても良さそう。
やるならフォローとリプライの監視かも

**Comment by neruneru0419** [comment]
了解
その方向でやるかあ

**Comment by ayok01** [comment]
https://qiita.com/CyberRex/items/e49828dba8e5867d8b26

**Comment by ayok01** [comment]
ここでやりたいことやってるから見てみるといいよ

**Comment by ayok01** [comment]
使用済み
